name = "leansec"
version = "0.1.0"
# keywords = ["math"]
defaultTargets = ["Leansec"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = true

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Leansec"
